### ISSUE TITLE
[PE-D] UG addclass

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-F11-1/tp#210]
I believe the format is supposed to be HH:MM-HH:MM but it seems that what you wrote on the UG was HH.MM-HH:MM, the first time has a '.' instead of ':'.

Also will the day be CAPS as in "MON" or will it be first letter caps as in "Tue". Based on what im seeing in your actual app. It seems to be the former.

![image.png](https://raw.githubusercontent.com/houtenteo/ped/main/files/5271025c-ff42-4da1-b661-9d67ccf0ab33.png)

very minor problems but may confuse readers.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: houtenteo/ped#5

**Comment by yourally2** [comment]
Thanks for spotting this!
