### ISSUE TITLE
[PE-D] Under Feature: Adding a student

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-F11-1/tp#225]
![image.png](https://raw.githubusercontent.com/chowRuiYan/ped/main/files/86b056cd-1902-4836-879a-9d9fe24fdd1b.png)

I think it should be `The segments are` ~~not~~  `fixed in order` instead.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: chowRuiYan/ped#3

**Comment by s7u4rt99** [comment]
This is the intended behavior, we can do phone then email or email then phone
